name: Deploy to Firebase

on:
  repository_dispatch:
    types: [deploy-setlist, new-concert, manual-deploy, photo-upload, photo-delete]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install firebase-admin

      - name: Update Service Worker cache version
        run: python3 scripts/update_cache_version.py

      - name: Export data from Firestore
        env:
          GOOGLE_CLOUD_PROJECT: earplugs-and-memories
        run: |
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > $HOME/gcloud-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-key.json
          python3 scripts/export_to_web.py

      - name: Clear Firebase CLI cache
        run: rm -rf .firebase/hosting*.cache

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --force --project earplugs-and-memories --token "$FIREBASE_TOKEN"
